version: "3.8"
services:
  api:
    ports: !reset  # Remove any exposed ports
      - "30080:3080"
    networks:
      - librechat_isolated
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:3080/health" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s


  client:
    ports: !reset []
    networks:
      - librechat_isolated
    command: "true"
    entrypoint: "true"
    volumes: !reset []

  mongodb:
    ports: !reset [ ]  # Remove any exposed ports
    networks:
      - librechat_isolated

  meilisearch:
    ports: !reset [ ]  # Remove any exposed ports
    networks:
      - librechat_isolated

  vectordb:
    ports: !reset [ ]  # Remove any exposed ports
    networks:
      - librechat_isolated

  rag_api:
    ports: !reset [ ]  # Remove any exposed ports
    networks:
      - librechat_isolated

networks:
  librechat_isolated:
    name: librechat_isolated
    driver: bridge